hello-world: hello-world.c
	gcc hello-world.c -o hello-world

hello-world2: hello-world2.cc
	g++ hello-world2.cc -o hello-world2

hello-world3: hello-world3.cc
	g++ hello-world3.cc -o hello-world3

all: hello-world hello-world2 hello-world3

clean:
	rm -f hello-world hello-world2 hello-world3